import type { Metadata } from "next";
import "./globals.css";
import { poppins, monalista } from './fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

<html lang="en" className={`${poppins.variable} ${monalista.variable}`}>
  <body className="font-sans">{children}</body>
</html>
  );
}
